
points:
  zones:
    matrix:
      anchor:
        shift: [150, -170]
      columns:
        outer:
          rows:
            bottom:
              skip: true
            top:
              row_net: P3
              column_net: P9
            home:
              row_net: P3
              column_net: P8
        pinky.key:
          stagger: 0.6U
          column_net: P9
        ring.key:
          stagger: 0.7U
          column_net: P8
        middle.key:
          stagger: 0.25U
          column_net: P7
        index.key:
          stagger: -0.25U
          column_net: P6
        inner.key:
          stagger: -0.15U
          column_net: P5 
      rows:
        bottom:
          row_net: P2
        home:
          row_net: P0
        top:
          row_net: P1
    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [-0.5U, -1.3U]
        rotate: 10
      columns:
        inner:
          key.column_net: P7
        home.key:
          splay: -10
          shift: [2.5, -1.5]
          column_net: P6
        outer.key:
          splay: -25
          shift: [8, 2]
          height: 1.5U
          column_net: P5
      rows:
        fan:
          row_net: P3

outlines:
  pcb:
    - what: rectangle
      where: true
      asym: source
      size: 20
      corner: 1
  polygon:
    - what: polygon # all borders
      operation: stack
      points:
        - ref: matrix_inner_top
        - ref: matrix_inner_top
          shift: [1.5U, 0]
        - ref: matrix_inner_bottom
          shift: [1.5U, -0.9U]
        - ref: thumb_outer_fan
          shift: [0.5U, -0.5U]
        - ref: thumb_home_fan
          shift: [0, -0.5U]
        - ref: thumb_inner_fan
          shift: [0U, -0.5U]
        - ref: thumb_inner_fan
          shift: [0U, 0.1U]
        - ref: matrix_pinky_bottom
          shift: [0, -0.53U]
        - ref: matrix_pinky_top
  trackpoint:
    - what: rectangle
      size: 3.1
      adjust: 
      - aggregate: 
          parts: [matrix_index_top, matrix_index_home, matrix_inner_top, matrix_inner_home]
          method: average
    - what: circle
      radius: 1.5
      adjust:
      - aggregate: 
          parts: [matrix_index_top, matrix_index_home, matrix_inner_top, matrix_inner_home]
          method: average
        shift: [10.5, 0]
    - what: circle
      radius: 1.5
      adjust:
      - aggregate: 
          parts: [matrix_index_top, matrix_index_home, matrix_inner_top, matrix_inner_home]
          method: average
        shift: [-10.5, 0]
    - what: rectangle
      size: 3.1
      adjust:
        - ref: matrix_index_bottom
          shift: [0U, -0.6U]
    - what: circle
      radius: 1.5
      adjust:
        - ref: matrix_index_bottom
          shift: [10.5, -0.6U]
    - what: circle
      radius: 1.5
      adjust:
        - ref: matrix_index_bottom
          shift: [-10.5, -0.6U]
    - what: rectangle
      size: 3.1
      adjust:
      - ref: matrix_inner_bottom
        shift: [0.32U, -0.65U]
    - what: circle
      radius: 1.5
      adjust:
      - ref: matrix_inner_bottom
        shift: [0.32U + 10.5, -0.65U]
    - what: circle
      radius: 1.5
      adjust:
      - ref: matrix_inner_bottom
        shift: [0.32U - 10.5, -0.65U]
    - what: rectangle
      size: 3.1
      adjust:
      - aggregate:
          parts: [matrix_inner_bottom, matrix_inner_home, matrix_index_bottom, matrix_index_home]
          method: average
    - what: circle
      radius: 1.5
      adjust:
      - aggregate:
          parts: [matrix_inner_bottom, matrix_inner_home, matrix_index_bottom, matrix_index_home]
          method: average
        shift: [10.5, 0]
    - what: circle
      radius: 1.5
      adjust:
      - aggregate:
          parts: [matrix_inner_bottom, matrix_inner_home, matrix_index_bottom, matrix_index_home]
          method: average
        shift: [-10.5, 0]
  pcb_perimeter:
    - what: outline # keys
      name: pcb
    - what: outline
      name: polygon
      operation: add
    - what: outline
      name: trackpoint
      operation: subtract
pcbs:
  trone:
    outlines:
      main:
        outline: pcb_perimeter
    footprints:
      keys:
        what: mx
        where: true
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          reverse: true
          keycaps: true
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      connector:
        what: jumper
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
      usbc:
        what: usbc
        params:
          A2: P3
          A5: P2
          A7: P0
          A10: P1
          B1: GND
          B2: RAW
          B3: P5
          B5: P6
          B8: P7
          B10: P8
          B11: P9
        adjust:
          ref: matrix_inner_bottom
          shift: [1.20U, -0.15U]
          rotate: 90
      mcu:
        what: promicro_with_bridges
        params:
          orientation: "up" # central side will be down
        where:
          ref: matrix_inner_top
          shift: [19,-18.5]
          rotate: -90


